name: GraphQL Query Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
