name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: ['a','b','c','d','e','f','g','h']
        bar: ['i','j','k','l','m','n','p','q']
        random: ['s','t','u','v']
    steps:
      - uses: actions/checkout@v3
  build2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: ['a','b','c','d','e','f','g','h']
        bar: ['i','j','k','l','m','n','p','q']
        random: ['s','t','u','v']
    steps:
      - uses: actions/checkout@v3


